# Generated by Django 2.0.4 on 2018-04-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantit', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.TimeField(auto_now=True)),
                ('stadus', models.CharField(choices=[('buy', 'Buy'), ('sales', 'Sales')], max_length=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Author')),
            ],
        ),
    ]
